name: run cmd on windows
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      #- name: echo a string
      #  run: echo "hello"
      - name: multiline string
        run: |
          node -v
          npm -v 
      - name: echo a string
        run: echo "hey"       
