name: Reusable Template

on:
  push:
  workflow_dispatch:   
jobs:
  call-workflow:    
     uses: sigmarpanda/github-actions-demo/.github/workflows/DockerImagebuild-push.yml@master
     secrets:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        JFROG_USER: ${{secrets.JFROG_USER}}
        JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
        
