# This is a basic workflow to help you get started with Actions
name: azure login

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1 
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS12}}
        enable-AzPSSession: true
    - name : install az pwsh cli   
      run: |
        Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
        Import-module -name Az.Sql   
        
    - name: Powershell script
      run:  set-AzContext -Subscription "05f10e8d-cec2-4d36-9144-7cbf3b611336"
      #run: ./azsttrigger.ps1
      shell: pwsh
      #run: ${{ github.action_path }}/azsttrigger.ps1
