# This is a basic workflow to help you get started with Actions
name: azure login

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS12}}
        enable-AzPSSession: true
        
    - name: ps script
      run: pwsh -command ".\$GITHUB_WORKSPACE\storage.ps1 -Arg1 'arguments n°1'"
    #- shell: pwsh
    #  run: .\storage.ps1
