name: Backup Sql for Github Actions

on: [push]
permissions:
  id-token: write
  contents: read
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS11 }}
        
        enable-AzPSSession: true       


# run az cmnd
  runs-azure-command:
    steps:
      shell: pwsh
      run: |
        az storage account create --name mygitstorage2 --resource-group Windapp --location "South India" --sku Standard_LRS
          

