name: test a new sample
on: [push]
jobs:
  runs-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string 
        run: echo "hey"
      - name: echo multiple string
        run: |
          npm -v
          node -v  
  runs-windows-command:
    runs-on: Windows-latest
    steps:
      - name: run ps command
        run: Write-Host "ps command"            
